[application]
name = "kopuz"
default_platform = "desktop"

[application.assets]
base_path = "crates/kopuz/assets"

[bundle]
identifier = "com.temidaradev.kopuz"
publisher = "temidaradev"
icon = ["assets/app.ico", "assets/logo.png"]
category = "public.app-category.music"
targets = ["macos", "dmg", "nsis", "msi"]

[bundle.macos]
info_plist_path = "Info.plist"
